export const initialFieldsData = {
  Date_Time: null,
  Location: null,
  Equipment_Type: null,
  Equipment_Model: null,
  Equipment: null,
  Working_Hours: null,
  Breakdown_Type: [],
  ProblemCreatedBy: null,
  Problem: null,
  Action: null,
  ResponseTime: null,
  Problem_start_From: null,
  problem_End_To: null,
  Breakdown_Time: null,
  Spare_part: null,
  ResponsibleEngineer: null,
  CheckTime: null,
  Status: null,
  Sent: null,
  Seen: null,
};
